apiVersion: v1
kind: Pod
metadata:
  name: debug-busybox
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: busybox
  nodeSelector:
    # specific node with hostname
    kubernetes.io/hostname: ip-10-1-2-3.ap-northeast-0.compute.internal