apiVersion: v1
kind: Pod
metadata:
  name: debug-netutils
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: hwchiu/netutils
      name: netutils

# Imperative way kubectl run hwchiu-pod --rm -it --image hwchiu/netutils -- /bin/bash