apiVersion: v1
kind: Pod
metadata:
  name: whoami-readiness
  labels:
    app: goproxy
spec:
  containers:
  - name: whoami
    image: traefik/whoami
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 1
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
