apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - selector:
          dnsZones:
          - "myhost"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: 
            accessKeyID: 
            secretAccessKeySecretRef:
              name: aws-route53-creds
              key: password.txt

