apiVersion: v1
kind: Service
metadata:
  name: whoami-ot-nlb
  labels:
    app: whoami
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
spec:
  type: LoadBalancer
  #  allocateLoadBalancerNodePorts: true
  #  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: whoami
  loadBalancerClass: service.k8s.aws/nlb