apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netutils
spec:
  selector:
    matchLabels:
      name: netutils
  template:
    metadata:
      labels:
        name: netutils
    spec:
      hostNetwork: true
      containers:
        - image: hwchiu/netutils
          name: netutils
          
